---
apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-namespace
  labels:
    app.kubernetes.io/name: fastapi-admin-app
    environment: production
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-admin-serviceaccount
  namespace: fastapi-namespace
