---
apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-namespace
  labels:
    app.kubernetes.io/name: fastapi-user-app
    environment: production
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-serviceaccount
  namespace: fastapi-namespace
  annotations:
    iam.gke.io/gcp-service-account: CHANGEME-gke-gsa-email
