---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fastapi-user-app-secrets
  namespace: fastapi-namespace
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/CHANGEME-gcp-project-number/secrets/fastapi-user-db-host/versions/latest"
        fileName: "fastapi-user-db-host"
      - resourceName: "projects/CHANGEME-gcp-project-number/secrets/fastapi-user-db-port/versions/latest"
        fileName: "fastapi-user-db-port"
      - resourceName: "projects/CHANGEME-gcp-project-number/secrets/fastapi-user-db-user/versions/latest"
        fileName: "fastapi-user-db-user"
      - resourceName: "projects/CHANGEME-gcp-project-number/secrets/fastapi-user-db-password/versions/latest"
        fileName: "fastapi-user-db-password"
      - resourceName: "projects/CHANGEME-gcp-project-number/secrets/fastapi-user-db-name/versions/latest"
        fileName: "fastapi-user-db-name"
      - resourceName: "projects/CHANGEME-gcp-project-number/secrets/fastapi-user-jwt-secret-key/versions/latest"
        fileName: "fastapi-user-jwt-secret-key"
  secretObjects:
    - secretName: fastapi-db-secret
      type: Opaque
      data:
        - objectName: fastapi-user-db-host
          key: shost
        - objectName: fastapi-user-db-port
          key: sport
        - objectName: fastapi-user-db-user
          key: suser
        - objectName: fastapi-user-db-password
          key: spassword
        - objectName: fastapi-user-db-name
          key: sdatabase
        - objectName: fastapi-user-jwt-secret-key
          key: SECRET_KEY
