---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-user-app
  namespace: fastapi-namespace
  labels:
    app: fastapi-user-app
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  selector:
    app: fastapi-user-app
  ports:
    - name: https
      port: 50443
      targetPort: 50443
      protocol: TCP
