apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - secretproviderclass.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

images:
  - name: us-east4-docker.pkg.dev/CHANGEME-gcp-project/CHANGEME-gcp-project/fastapi-admin-app
    newName: us-east4-docker.pkg.dev/CHANGEME-gcp-project/CHANGEME-gcp-project/fastapi-admin-app
    newTag: latest
