---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fastapi-user-app-secrets
  namespace: fastapi-namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "CHANGEME-azure-keyvault-client-id"
    keyvaultName: "CHANGEME-azure-keyvault-name"
    tenantId: "CHANGEME-azure-tenant-id"
    objects: |
      array:
        - |
          objectName: fastapi-user-db-host
          objectType: secret
        - |
          objectName: fastapi-user-db-port
          objectType: secret
        - |
          objectName: fastapi-user-db-user
          objectType: secret
        - |
          objectName: fastapi-user-db-password
          objectType: secret
        - |
          objectName: fastapi-user-db-name
          objectType: secret
        - |
          objectName: fastapi-user-jwt-secret-key
          objectType: secret
  secretObjects:
    - secretName: fastapi-db-secret
      type: Opaque
      data:
        - objectName: fastapi-user-db-host
          key: shost
        - objectName: fastapi-user-db-port
          key: sport
        - objectName: fastapi-user-db-user
          key: suser
        - objectName: fastapi-user-db-password
          key: spassword
        - objectName: fastapi-user-db-name
          key: sdatabase
        - objectName: fastapi-user-jwt-secret-key
          key: SECRET_KEY
