apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - secretproviderclass.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

images:
  - name: CHANGEME-ecr-registry-host/fastapi-user-app
    newName: CHANGEME-ecr-registry-host/fastapi-user-app
    newTag: latest
