---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-user-app
  namespace: fastapi-namespace
  labels:
    app: fastapi-user-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "50443"
spec:
  type: LoadBalancer
  selector:
    app: fastapi-user-app
  ports:
    - name: https
      port: 50443
      targetPort: 50443
      protocol: TCP
  sessionAffinity: None
