---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fastapi-admin-app-secrets
  namespace: fastapi-namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "CHANGEME-aws-secrets-manager-secret-arn"
        objectAlias: "fastapi-admin-db-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: shost
            objectAlias: fastapi-admin-db-host
          - path: sport
            objectAlias: fastapi-admin-db-port
          - path: suser
            objectAlias: fastapi-admin-db-user
          - path: spassword
            objectAlias: fastapi-admin-db-password
          - path: sdatabase
            objectAlias: fastapi-admin-db-name
          - path: SECRET_KEY
            objectAlias: fastapi-admin-jwt-secret-key
  secretObjects:
    - secretName: fastapi-admin-db-secret
      type: Opaque
      data:
        - objectName: fastapi-admin-db-host
          key: shost
        - objectName: fastapi-admin-db-port
          key: sport
        - objectName: fastapi-admin-db-user
          key: suser
        - objectName: fastapi-admin-db-password
          key: spassword
        - objectName: fastapi-admin-db-name
          key: sdatabase
        - objectName: fastapi-admin-jwt-secret-key
          key: SECRET_KEY
