---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-admin-gke
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skondla/fastAPIWebApp.git
    targetRevision: main
    path: gcp/gke/deploy/manifests/fastapi-admin
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
