#!/usr/bin/env python3
# Author: skondla@me.com
# Purpose: AI runbook & postmortem generator. Drafts (1) blameless
#          postmortems from incident-channel logs, and (2) operational
#          runbooks for alerts, in this repo's house format. Output is a
#          DRAFT for human review — commit only after correction.
#
# Usage:
#   python ai/runbooks/generate_runbook.py postmortem --input incident-log.txt
#   python ai/runbooks/generate_runbook.py runbook --title FastApiLatencyP95High \
#       --input kubernetes/observability/prometheus-rules.yaml
# -*- coding: utf-8 -*-

import argparse
import os
import sys
from datetime import datetime, timezone

from anthropic import Anthropic

MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-opus-4-8")

POSTMORTEM_SYSTEM = """\
You write blameless postmortems for a FastAPI-on-Kubernetes system delivered
via ArgoCD GitOps (rollback = `argocd app rollback`, never kubectl edits),
with SLOs defined in docs/slo.md (99.5% availability, p95 < 500ms).

From the raw incident log you receive, produce a postmortem in GitHub
markdown with exactly these sections:
# Postmortem: <one-line title>
## Impact  (duration, SLIs affected, error-budget consumed — compute it if
timestamps allow, state assumptions if not)
## Timeline  (UTC table: time | event | source — only events supported by the
log; never invent times)
## Root cause  (the causal chain, not a person)
## What went well / What went poorly
## Action items  (table: item | type [prevent/detect/mitigate] | owner TBD |
suggested issue title)

Blameless means systems and processes fail, not people — name roles, not
individuals. Where the log is ambiguous, say so explicitly rather than
guessing.
"""

RUNBOOK_SYSTEM = """\
You write operational runbooks for on-call engineers of a FastAPI-on-
Kubernetes system (namespaces fastapi-namespace / fastapi-admin-namespace,
ArgoCD delivery, Prometheus/Grafana observability, Redis-backed token store,
RDS/Aurora database).

Given an alert name and its rule/context, produce a runbook in GitHub
markdown with exactly these sections:
# Runbook: <alert name>
## Meaning  (what fired and what it implies for users, 2-3 sentences)
## Verify  (commands/queries to confirm it's real, not a monitoring artifact)
## Diagnose  (ordered checks, most-likely first, with exact kubectl/PromQL/
argocd commands)
## Mitigate  (safe actions in order of preference; GitOps rollback before
scaling before anything manual; flag anything destructive with ⚠️)
## Escalate  (when to page up, per docs/governance/incident-response.md)

Commands must be copy-pasteable and correct for the resources named in the
provided context. Never include a destructive command without a ⚠️ line
explaining the blast radius.
"""


def generate(system: str, user_prompt: str) -> str:
    client = Anthropic()
    with client.messages.stream(
        model=MODEL,
        max_tokens=16000,
        thinking={"type": "adaptive"},
        system=system,
        messages=[{"role": "user", "content": user_prompt}],
    ) as stream:
        message = stream.get_final_message()
    return next(b.text for b in message.content if b.type == "text")


def main() -> int:
    parser = argparse.ArgumentParser(description="AI runbook/postmortem generator")
    sub = parser.add_subparsers(dest="mode", required=True)

    pm = sub.add_parser("postmortem", help="draft a postmortem from an incident log")
    pm.add_argument("--input", required=True, help="incident log file ('-' for stdin)")
    pm.add_argument("--output", default=None)

    rb = sub.add_parser("runbook", help="draft a runbook for an alert")
    rb.add_argument("--title", required=True, help="alert name")
    rb.add_argument("--input", default=None,
                    help="context file, e.g. the PrometheusRule yaml")
    rb.add_argument("--output", default=None)

    args = parser.parse_args()

    def read(path):
        return sys.stdin.read() if path == "-" else open(path).read()

    if args.mode == "postmortem":
        prompt = "Incident log:\n\n" + read(args.input)
        out = args.output or f"postmortem-draft-{datetime.now(timezone.utc):%Y%m%d}.md"
        text = generate(POSTMORTEM_SYSTEM, prompt)
    else:
        context = read(args.input) if args.input else "(no extra context provided)"
        prompt = f"Alert: {args.title}\n\nContext:\n\n{context}"
        out = args.output or f"runbook-{args.title}.md"
        text = generate(RUNBOOK_SYSTEM, prompt)

    banner = ("<!-- DRAFT generated by ai/runbooks/generate_runbook.py "
              f"({MODEL}). Review and correct before committing. -->\n\n")
    with open(out, "w") as fh:
        fh.write(banner + text + "\n")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
